CLUSTER_VERSION=latest
NUM_NODES=50
MACHINE_TYPE=n1-standard-8
AVAILABILITY_ZONE=us-central1-a
ISTIO_VERSION=1.3.5
DATAPLANE_NUM_CONNECTIONS=10

NUM_APPS=1000 # must be equal to or larger than NUM_USERS
NUM_USERS=100
USER_DELAY=1
