apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - args:
    - sleep
    - "10000000"
    image: ubuntu
    name: ubuntu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    scalers.cp: dedicated
  tolerations:
    - effect: NoSchedule
      key: scalers.cp
      operator: Equal
      value: dedicated

status: {}
